# Generated by Django 3.2.6 on 2021-09-03 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentaed',
            name='lat',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='currentaed',
            name='lon',
            field=models.FloatField(),
        ),
    ]
