# Generated by Django 3.2.7 on 2022-03-12 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Integer',
        ),
        migrations.DeleteModel(
            name='String',
        ),
        migrations.AddField(
            model_name='ohca',
            name='covered',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
