# Generated by Django 3.2.7 on 2022-03-12 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20220312_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='ohca',
            name='postalCode',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
