# Generated by Django 3.2.6 on 2021-09-03 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20210903_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentaed',
            name='country',
            field=models.CharField(default='singapore', max_length=200),
        ),
        migrations.AddField(
            model_name='currentaed',
            name='pa',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='currentaed',
            name='region',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='currentaed',
            name='subzone',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
