# Generated by Django 3.2.6 on 2021-09-03 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20210903_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentaed',
            name='region',
            field=models.CharField(blank=True, choices=[('N', 'North'), ('S', 'South'), ('E', 'East'), ('W', 'West')], max_length=200, null=True),
        ),
    ]
