# Generated by Django 3.2.7 on 2022-03-17 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_ohca_postalcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='ohca',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
