# Generated by Django 3.2.7 on 2022-03-17 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_ohca_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='ohca',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ohca',
            name='gender',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ohca',
            name='race',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
