# Generated by Django 3.2.7 on 2022-03-21 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20220317_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ohca',
            name='subzone',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
